# GitHub Actions 工作流配置文件
name: KeepS00

# 触发条件：当代码推送到 main 分支或创建 Pull Request 时触发
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # 作业名称：运行 SSH 命令
  KeepS00:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行器
    env:
      # 从 GitHub Secrets 中获取配置，配置内容存储在 CONFIG 环境变量中
      CONFIG: ${{ secrets.CONFIG }}
    steps:
      # 步骤 1：检出仓库代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 步骤 2：设置 Python 环境
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 使用 Python 3.x 版本

      # 步骤 3：安装所需依赖
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install paramiko PyYAML

      # 步骤 4：运行 SSH 命令脚本（q.py）
      - name: 运行 SSH 命令脚本
        run: python KeepS00.py
