name: KeepS00
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次（整点触发）
  workflow_dispatch:
jobs:
  KeepS00:
    runs-on: ubuntu-latest
    env:
      # 如果使用 Variables，需要修改这行
      CONFIG: ${{ vars.CONFIG }}  # 修改这里从 secrets 改为 vars
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install paramiko PyYAML
      
      - name: 运行 SSH 命令脚本
        run: python KeepS00.py
